#!/bin/bash
# respond_to_claude.sh — Codex-side helper that archives codex_response.md and
# doorbells Claude. Writing codex_response.md alone is not protocol-complete.

set -euo pipefail

INTERAGENT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(dirname "$INTERAGENT_DIR")"
PROJECT_NAME="$(basename "$PROJECT_DIR")"
BROKER="${INTERAGENT_DIR}/broker.mjs"
NORMALIZE_SCRIPT="${INTERAGENT_DIR}/normalize_claude_session.sh"
RESPONSE_FILE="${INTERAGENT_DIR}/codex_response.md"
SESSION="claude-${PROJECT_NAME}"
ADVERSARIAL_REVIEW_PHRASE="PER .interagent/docs/INTERAGENT_PROTOCOL.md (READ IT)"
DOORBELL_MARKER="CODEX RESPONSE DOORBELL GENERATED BY .interagent/respond_to_claude.sh:"
CLEAR_POINTER="${INTERAGENT_CLEAR_POINTER:-claude_response}"
TASK_ID_ARGS=()

if [[ -n "${INTERAGENT_TASK_ID:-}" ]]; then
    TASK_ID_ARGS=(--task-id "$INTERAGENT_TASK_ID")
fi

if [[ ! -f "$RESPONSE_FILE" ]]; then
    echo "[ERROR] Response file not found: $RESPONSE_FILE"
    exit 1
fi
if [[ ! -s "$RESPONSE_FILE" ]]; then
    echo "[ERROR] Response file is empty: $RESPONSE_FILE"
    echo "        Write the Codex -> Claude response before sending."
    exit 1
fi
if [[ ! -f "$BROKER" ]]; then
    echo "[ERROR] Broker not found: $BROKER"
    exit 1
fi
if [[ ! -x "$NORMALIZE_SCRIPT" ]]; then
    echo "[ERROR] Normalize script not executable: $NORMALIZE_SCRIPT"
    exit 1
fi
if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    echo "[ERROR] tmux session '$SESSION' is not running."
    echo "        Start Claude: ./.interagent/start_claude.sh"
    exit 1
fi

RESPONSE_TEXT="$(cat "$RESPONSE_FILE")"
if ! printf '%s\n' "$RESPONSE_TEXT" | grep -Fq "$ADVERSARIAL_REVIEW_PHRASE"; then
    echo "[ERROR] Response is missing the mandatory adversarial-review continuation phrase."
    echo "        Required exact phrase:"
    echo "        $ADVERSARIAL_REVIEW_PHRASE"
    echo "        Every review-loop response must instruct the receiver to continue independent adversarial review."
    exit 1
fi

"$BROKER" ensure >/dev/null

if ! "$BROKER" clear-pointer --pointer "$CLEAR_POINTER" >/dev/null 2>&1; then
    echo "[ERROR] Inbound pointer still contains unread or mismatched content: $CLEAR_POINTER"
    echo "        Set INTERAGENT_CLEAR_POINTER to the actual inbound pointer for this response, or process it first."
    exit 1
fi

ARCHIVED_RESPONSE="$("$BROKER" archive-response --from codex --to claude --source "$RESPONSE_FILE" "${TASK_ID_ARGS[@]}")"

"$NORMALIZE_SCRIPT" --reason "before-response-doorbell" --quiet || true
DOORBELL="${DOORBELL_MARKER} A review response from Codex is ready at .interagent/codex_response.md. ADVERSARIAL REVIEW REQUIRED: ${ADVERSARIAL_REVIEW_PHRASE}. Use staged context: read findings headers/file refs first, walk cited code/diff, then read the full response and continue."
DOORBELL_LEN=${#DOORBELL}
if [[ $DOORBELL_LEN -gt 500 ]]; then
    echo "[WARN] Doorbell is $DOORBELL_LEN chars — that's too long."
    echo "       The doorbell is a pointer, not the mail. Put details in the response file."
    echo "       Sending anyway, but the TUI may require a manual second Enter."
fi
tmux send-keys -t "$SESSION" -l "$DOORBELL"
sleep 0.3
tmux send-keys -t "$SESSION" Enter
sleep 0.3
tmux send-keys -t "$SESSION" Enter

TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"
echo "[sent] $TIMESTAMP — Codex response archived and doorbelled to '$SESSION'"
echo "[history] archived response: $ARCHIVED_RESPONSE"
echo "[state] cleared inbound pointer: $CLEAR_POINTER"
