#!/bin/bash
# send_to_claude.sh — Codex-side helper that archives a request for Claude and
# delivers an explicit tmux doorbell telling Claude to start with Review Seed.

set -euo pipefail

INTERAGENT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(dirname "$INTERAGENT_DIR")"
PROJECT_NAME="$(basename "$PROJECT_DIR")"
BROKER="${INTERAGENT_DIR}/broker.mjs"
NORMALIZE_SCRIPT="${INTERAGENT_DIR}/normalize_claude_session.sh"
REQUEST_FILE="${INTERAGENT_DIR}/codex_request.md"
RESPONSE_FILE="${INTERAGENT_DIR}/claude_response.md"
DISABLE_FLAG="${INTERAGENT_DIR}/CLAUDE_DOORBELL_DISABLED"
SESSION="claude-${PROJECT_NAME}"
ADVERSARIAL_REVIEW_PHRASE="PER .interagent/docs/INTERAGENT_PROTOCOL.md (READ IT)"
DOORBELL_MARKER="CODEX DOORBELL GENERATED BY .interagent/send_to_claude.sh:"
TASK_ID_ARGS=()

if [[ -n "${INTERAGENT_TASK_ID:-}" ]]; then
    TASK_ID_ARGS=(--task-id "$INTERAGENT_TASK_ID")
fi

if [[ ! -f "$REQUEST_FILE" ]]; then
    echo "[ERROR] Request file not found: $REQUEST_FILE"
    exit 1
fi
if [[ ! -s "$REQUEST_FILE" ]]; then
    echo "[ERROR] Request file is empty: $REQUEST_FILE"
    echo "        Write the Codex -> Claude request before sending."
    exit 1
fi
if [[ ! -f "$BROKER" ]]; then
    echo "[ERROR] Broker not found: $BROKER"
    exit 1
fi
if [[ ! -x "$NORMALIZE_SCRIPT" ]]; then
    echo "[ERROR] Normalize script not executable: $NORMALIZE_SCRIPT"
    exit 1
fi
if [[ -f "$DISABLE_FLAG" ]]; then
    echo "[ERROR] Claude doorbells are disabled via: $DISABLE_FLAG"
    echo "        Remove that file to re-enable Codex -> Claude review requests."
    exit 1
fi

REQUEST_TEXT="$(cat "$REQUEST_FILE")"
REQUEST_TYPE="$(printf '%s\n' "$REQUEST_TEXT" | sed -n 's/^\*\*Type:\*\*[[:space:]]*//p' | head -1)"
if printf '%s\n' "$REQUEST_TYPE" | grep -Eiq 'review'; then
    if ! printf '%s\n' "$REQUEST_TEXT" | grep -Fq "$ADVERSARIAL_REVIEW_PHRASE"; then
        echo "[ERROR] Review request is missing the mandatory adversarial-review header."
        echo "        Required exact phrase:"
        echo "        $ADVERSARIAL_REVIEW_PHRASE"
        echo "        Add .interagent/adversarial_review_header.md at the top of codex_request.md."
        exit 1
    fi
    if ! printf '%s\n' "$REQUEST_TEXT" | grep -Eq '^#{2,3}[[:space:]]+Review Seed[[:space:]]*$'; then
        echo "[ERROR] Review request is missing the mandatory Review Seed section."
        echo "        Add '### Review Seed' near the top with role, changed files, progress file, and diff locator."
        exit 1
    fi
fi

"$BROKER" ensure >/dev/null

if [[ -s "$RESPONSE_FILE" ]]; then
    if ! "$BROKER" clear-pointer --pointer claude_response >/dev/null 2>&1; then
        echo "[ERROR] Response pointer still contains unread or mismatched content: $RESPONSE_FILE"
        echo "        Read/process that mailbox first; refusing to auto-archive it under the current task."
        exit 1
    fi
else
    : > "$RESPONSE_FILE"
fi

ARCHIVED_REQUEST="$("$BROKER" archive-request --from codex --to claude --source "$REQUEST_FILE" "${TASK_ID_ARGS[@]}")"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"

echo "[sent] $TIMESTAMP — Codex request archived for Claude"
echo "[history] archived request: $ARCHIVED_REQUEST"
echo "[state] cleared claude_response.md pointer for a fresh reply"

if tmux has-session -t "$SESSION" 2>/dev/null; then
    "$NORMALIZE_SCRIPT" --reason "before-doorbell" --quiet || true
    if printf '%s\n' "$REQUEST_TYPE" | grep -Eiq 'review'; then
        DOORBELL="A review request is parked at .interagent/codex_request.md. ADVERSARIAL REVIEW REQUIRED: ${ADVERSARIAL_REVIEW_PHRASE}. Use staged context: read only the header + Review Seed, run the diff locator and code-first scan, then read the rest. Respond to .interagent/claude_response.md."
    else
        DOORBELL="A request from Codex is ready at .interagent/codex_request.md. Read it in full and write your response to .interagent/claude_response.md."
    fi
    DOORBELL="${DOORBELL_MARKER} ${DOORBELL}"
    DOORBELL_LEN=${#DOORBELL}
    if [[ $DOORBELL_LEN -gt 500 ]]; then
        echo "[WARN] Doorbell is $DOORBELL_LEN chars — that's too long."
        echo "       The doorbell is a pointer, not the mail. Put details in the request file."
        echo "       Sending anyway, but the TUI may require a manual second Enter."
    fi
    tmux send-keys -t "$SESSION" -l "$DOORBELL"
    sleep 0.3
    tmux send-keys -t "$SESSION" Enter
    sleep 0.3
    tmux send-keys -t "$SESSION" Enter
    echo "[doorbell] typed into tmux session '$SESSION'"
else
    echo "[warn] Claude tmux session '$SESSION' is not running."
    echo "       Request was archived, but no live doorbell was delivered."
    echo "       Start Claude with ./.interagent/start_claude.sh or manually doorbell a running Claude session."
fi

echo "[next] Run ./.interagent/wait_for_claude.sh if you want to block for the reply."
