#!/bin/bash
# send_to_codex.sh — Claude Code helper that delivers a doorbell to Codex.
#
# Flow:
#   1. Claude has already written the request file (.interagent/claude_request.md)
#   2. This script verifies the file exists and is non-empty
#   3. It clears codex_response.md so Claude can detect a fresh write
#   4. It uses `tmux send-keys` to type a short doorbell line into Codex's TUI
#      input box (as if the developer typed it), followed by Enter
#
# Usage:
#   ./.interagent/send_to_codex.sh
#   ./.interagent/send_to_codex.sh "Custom doorbell text for Codex"
#
# The first form uses a default doorbell; the second form lets Claude override
# (for example, to ask Codex to re-read a specific section only).

set -euo pipefail

INTERAGENT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(dirname "$INTERAGENT_DIR")"
PROJECT_NAME="$(basename "$PROJECT_DIR")"
BROKER="${INTERAGENT_DIR}/broker.mjs"
ADVERSARIAL_REVIEW_PHRASE="PER .interagent/docs/INTERAGENT_PROTOCOL.md (READ IT)"
DOORBELL_MARKER="CLAUDE DOORBELL GENERATED BY .interagent/send_to_codex.sh:"
TASK_ID_ARGS=()

if [[ -n "${INTERAGENT_TASK_ID:-}" ]]; then
    TASK_ID_ARGS=(--task-id "$INTERAGENT_TASK_ID")
fi

REQUEST_FILE="${INTERAGENT_DIR}/claude_request.md"
RESPONSE_FILE="${INTERAGENT_DIR}/codex_response.md"
SESSION="codex-${PROJECT_NAME}"

# 1. Request file must exist and be non-empty
if [[ ! -f "$REQUEST_FILE" ]]; then
    echo "[ERROR] Request file not found: $REQUEST_FILE"
    echo "        Write the request markdown before calling this script."
    exit 1
fi
if [[ ! -s "$REQUEST_FILE" ]]; then
    echo "[ERROR] Request file is empty: $REQUEST_FILE"
    echo "        Add review/implementation details before sending."
    exit 1
fi
if [[ ! -f "$BROKER" ]]; then
    echo "[ERROR] Broker not found: $BROKER"
    exit 1
fi

REQUEST_TEXT="$(cat "$REQUEST_FILE")"
REQUEST_TYPE="$(printf '%s\n' "$REQUEST_TEXT" | sed -n 's/^\*\*Type:\*\*[[:space:]]*//p' | head -1)"
if printf '%s\n' "$REQUEST_TYPE" | grep -Eiq 'review'; then
    if ! printf '%s\n' "$REQUEST_TEXT" | grep -Fq "$ADVERSARIAL_REVIEW_PHRASE"; then
        echo "[ERROR] Review request is missing the mandatory adversarial-review header."
        echo "        Required exact phrase:"
        echo "        $ADVERSARIAL_REVIEW_PHRASE"
        echo "        Add .interagent/adversarial_review_header.md at the top of claude_request.md."
        exit 1
    fi
    if ! printf '%s\n' "$REQUEST_TEXT" | grep -Eq '^#{2,3}[[:space:]]+Review Seed[[:space:]]*$'; then
        echo "[ERROR] Review request is missing the mandatory Review Seed section."
        echo "        Add '### Review Seed' near the top with role, changed files, progress file, and diff locator."
        exit 1
    fi
fi

"$BROKER" ensure >/dev/null

# 2. Verify the tmux session is alive
if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    echo "[ERROR] tmux session '$SESSION' is not running."
    echo "        Start Codex:  ./.interagent/start_codex.sh"
    exit 1
fi

# 3. Archive the request into durable history before delivery
ARCHIVED_REQUEST="$("$BROKER" archive-request --from claude --to codex --source "$REQUEST_FILE" "${TASK_ID_ARGS[@]}")"

# 4. Reset the response pointer only if its current contents are already archived
if [[ -s "$RESPONSE_FILE" ]]; then
    if ! "$BROKER" clear-pointer --pointer codex_response >/dev/null 2>&1; then
        echo "[ERROR] Response pointer still contains unread or mismatched content: $RESPONSE_FILE"
        echo "        Read/process that mailbox first; refusing to auto-archive it under the current task."
        exit 1
    fi
else
    : > "$RESPONSE_FILE"
fi

# 5. Compose the doorbell message (kept short — the real content is in the request file)
if [[ $# -ge 1 && -n "$1" ]]; then
    DOORBELL="$1"
else
    if printf '%s\n' "$REQUEST_TYPE" | grep -Eiq 'review'; then
        DOORBELL="A review request is parked at .interagent/claude_request.md. Use staged context: read only the header + Review Seed, run the diff locator and code-first scan, then read the rest. Write .interagent/codex_response.md."
    else
        DOORBELL="A request is ready at .interagent/claude_request.md. Read it in full, follow AGENTS.md plus .interagent/docs/INTERAGENT_PROTOCOL.md, and write .interagent/codex_response.md."
    fi
fi
if printf '%s\n' "$REQUEST_TYPE" | grep -Eiq 'review'; then
    DOORBELL="ADVERSARIAL REVIEW REQUIRED: ${ADVERSARIAL_REVIEW_PHRASE}. ${DOORBELL}"
fi
DOORBELL="${DOORBELL_MARKER} ${DOORBELL}"

# 6. Doorbell length guard.
#    The doorbell is a POINTER, not the mail. Keep it under ~300 chars so the
#    TUI accepts it as normal input. Long pastes (>~500 chars) trigger Codex's
#    "Pasted Content" preview mode which swallows the first Enter and leaves
#    the content as unsubmitted draft — wasting the entire blocking window.
#    If the doorbell is too long, the caller is stuffing findings into the
#    doorbell instead of putting them in the request file where they belong.
DOORBELL_LEN=${#DOORBELL}
if [[ $DOORBELL_LEN -gt 500 ]]; then
    echo "[WARN] Doorbell is $DOORBELL_LEN chars — that's too long."
    echo "       The doorbell is a pointer, not the mail. Put details in the request file."
    echo "       Sending anyway, but the TUI may require a manual second Enter."
fi

# 7. Send the doorbell as simulated keystrokes into the Codex TUI.
#    `-l` sends the string literally (no tmux key-name expansion like "C-b").
#    Two Enter presses with a pause between: the first either submits directly
#    (short doorbells) or confirms the paste preview (long doorbells); the
#    second submits after paste-preview confirmation, or is harmless if the
#    first already submitted (Codex ignores Enter on an empty input box).
tmux send-keys -t "$SESSION" -l "$DOORBELL"
sleep 0.3
tmux send-keys -t "$SESSION" Enter
sleep 0.3
tmux send-keys -t "$SESSION" Enter

TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"
echo "[sent] $TIMESTAMP — doorbell typed into tmux session '$SESSION'"
echo "[history] archived request: $ARCHIVED_REQUEST"
echo "[next] Run ./.interagent/wait_for_codex.sh to block until Codex responds."
